<?php

namespace webd\odt2html;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-30 at 10:16:04.
 */
class ODT2HTMLTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ODT2HTML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ODT2HTML;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\odt2html\ODT2HTML::odt2html
     * @todo   Implement testOdt2html().
     */
    public function testOdt2html() {
        $odt_file = dirname(__FILE__) . "/../../../Test document.odt";
        $odt2html = new ODT2HTML($odt_file);
        $result = $odt2html->parse();
        file_put_contents("/home/tibo/Desktop/result.html", $result);
    }
    
    public function testIN005() {
        $odt_file = "/home/tibo/Dropbox/ERM/IN005 Labs/IN005_session1.odt";
        $odt2html = new ODT2HTML($odt_file);
        $result = $odt2html->parse();
        file_put_contents("/home/tibo/Desktop/result-in005.html", $result);
    }

}
